#include <fstream>
#include <sstream>
#include <iostream>
#include <string>
#include <vector>
#include <cstdlib>
#include "hand.h"
#include "disenchant.h"
#include "card.h"
#include "deck.h"
#include "player.h"
#include "game.h"
#include "airelemental.h"
#include "earthelemental.h"
#include "banish.h"
#include "raisedead.h"
#include "blizzard.h"
#include "unsummon.h"
#include "giantstrength.h"
#include "potionseller.h"
#include "fireelemental.h"
#include "bonegolem.h"
#include "ascii_graphics.h"
#include "enrage.h"
#include "haste.h"
#include "magicfatigue.h"
#include "silence.h"
#include "mastersummoner.h"
#include "apprenticesummoner.h"
#include "recharge.h"
#include "novicepyromancer.h"
#include "darkritual.h"
#include "auraofpower.h"
#include "standstill.h"
